version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=network_inventory
      - POSTGRES_PASSWORD=password

  backend:
    image: ghcr.io/network-inventory/ni-backend/ni-backend:latest
    environment:
      - DJANGO_SETTINGS_MODULE=network_inventory.settings.docker
      - DJANGO_SECRET_KEY=foo
      - NI_MODE=development
      - POSTGRES_DB=network_inventory
      - POSTGRES_PASSWORD=password
      - NI_HOST
    depends_on:
      - db
    ports:
      - 80:8000

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/app
