version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD

  backend:
    image: ghcr.io/network-inventory/ni-backend/ni-backend:latest
    environment:
      - DJANGO_SETTINGS_MODULE
      - DJANGO_SECRET_KEY
      - NI_HOST
      - NI_MODE
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    depends_on:
      - db
    ports:
      - 80:8000
